export const UPDATE_DATA_ARRAY = "GENERATE_DATA_ARRAY";
export const TOGGLE_PLOT_DIRECTION = "TOGGLE_PLOT_DIRECTION";
export const UPDATE_DATA_ARRAY_SIZE = "UPDATE_DATA_ARRAY_SIZE";
export const IS_SORT_RUNNING = "IS_SORT_RUNNING";
